import Footer from '@/components/Footer'
import Footer2 from '@/components/Footer2'
import Head from 'next/head'
import { useEffect, useState } from 'react'

export default function About() {

    const [disableSendBtn, setDisableSendBtn] = useState(true);
    const [email, setEmail] = useState('');
    const [emailErr, setEmailErr] = useState('');
    const validEmail = new RegExp(/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/);
    const validate = () => {
        !validEmail.test(email) && email !== "" ? setEmailErr('Invalid email') : setEmailErr('')
    }
    const toggleDisable = () => {
        validEmail.test(email) ? setDisableSendBtn(false) : setDisableSendBtn(true)
    }
    const onChangeEmail = (e) => {
        setEmail(e.target.value)
    }

    const submitEmail = async (e) => {
        e.preventDefault();

        setTimeout(() => {
            setEmail('');
        }, 150);

        const form = {
            email,
        }

        const response = await fetch('../api/submit', {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(form)
        })

        const content = await response.json();

    }

    useEffect(() => {
        validate();
        toggleDisable();
    }, [email])

    return (
        <>
            <Head>
                <title>HybOrg</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className='w-full bg-[#0B0B0B]'>
                    <div className='container mx-auto'>
                        <div className='flex flex-col items-center lg:items-start px-6 pb-7'>
                            <div className='mt-[60px] mb-6'>
                                <img src={"./Logo.svg"} />
                            </div>
                            <div className='px-3 mb-5 lg:mb-10 max-w-[500px] lg:max-w-full'>
                                <h1 className='text-white text-[24px] leading-7 font-bold mb-5 lg:text-4xl'>Hello</h1>
                                <h2 className='text-[#AAAAAA] text-[14px] leading-4 lg:text-lg'>HybOrg is sustainable hybrid fashion brand. This product will be our MVP version.</h2>
                            </div>
                            <div className='lg:grid grid-cols-3 gap-10'>
                                <div>
                                    <div className='relative max-w-[500px]'>
                                        <img className='w-full' src={"./HybridVest.svg"} />
                                        <div className='flex gap-2 absolute top-3 left-3 pl-1 py-1 pr-3 rounded-full justify-center items-center bg-white/5'>
                                            <img src={"./Logobnw.svg"} />
                                            <h1 className='text-[16px] font-bold text-white uppercase'>Hybrid Vest</h1>
                                        </div>
                                        <div className='absolute top-3 right-5 p-2 bg-white/5 rounded-lg'>
                                            <img src={"./LucideIcon.svg"} />
                                        </div>
                                    </div>
                                    <div className='max-w-[500px] bg-[#1D1D1D] rounded-b-xl p-5 mb-4'>
                                        <p className='text-[#AAAAAA] text-[14px] leading-4'>
                                            Hybrid fashion is sustainable yet trendy. By owning only one HybOrg clothes, people can express themselves with limitless zero-waste hybrid looks across real and digital worlds.
                                            <br /><br />
                                            ・Get your unique upcycled garment<br />
                                            ・Style yourself with its AR counterparts<br />
                                            ・Express yourself across real and digital worlds without waste!<br />
                                            ・Wear them longer without get bored
                                        </p>
                                    </div>
                                </div>
                                <div className='max-w-[500px] bg-[#1D1D1D] rounded-xl p-5 mb-4'>
                                    <h1 className='text-white text-[24px] leading-7 font-bold mb-4'>HybOrg NFC Chip</h1>
                                    <div className='relative w-full mb-4'>
                                        <img className='w-full' src={"./NfcBg.svg"} />
                                        <div className='absolute top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%]' >
                                            <img src={"./NfcChip.svg"} />
                                        </div>
                                    </div>
                                    <p className='text-[#AAAAAA] text-[14px] leading-4'>Монгол уужыг та зөвхөн Hyborg tag ашиглан өмсөх боломжтой. Уг tag-н тусгай код хадгалж байгаа тул та нугалж гэмтээхгүй, бахархалтайгаар хадгалж яваарай.</p>
                                </div>
                                <div className='max-w-[500px] bg-[#1D1D1D] rounded-xl p-5 mb-4'>
                                    <h1 className='text-white text-[24px] leading-7 font-bold mb-4'>Virtual Wearable
                                        <br /><span className='text-[#CD5152]'>Bio expression</span></h1>
                                    <div className='relative w-full mb-4'>
                                        <img className='w-full' src={"./Wearable.svg"} />
                                        <div className='absolute bottom-3 left-3'>
                                            <img src={"./SnapChat.svg"} />
                                        </div>
                                    </div>
                                    <p className='text-[#AAAAAA] text-[14px] leading-4 mb-4'>Та эзэмшиж буй виртуал хувцасаа өөрийн бие дээрээ өмсөхийн тулд AR технологийг ашиглах хэрэгтэй тул та Snapchat аппликэйшинийг татаарай.</p>
                                    <a target='_blank' href="https://www.snapchat.com/unlock/?type=SNAPCODE&uuid=c0c61b978a7940ec88b9d97e73daac21&metadata=01"><button className='bg-[#CD5152] flex justify-center text-white gap-3 py-3 w-full rounded-2xl'>
                                        <img src={"./LucideIcon2.svg"} />
                                        <span className='text-[16px]'>Let's Hybrid Look</span>
                                    </button>
                                    </a>
                                </div>
                            </div>
                            <div className='lg:grid grid-cols-3 gap-10'>
                                <div></div>
                                <div></div>
                                <div className='max-w-[500px] bg-[#1D1D1D] rounded-xl p-5 mb-4 lg:mt-6 lg:hidden'>
                                    <h1 className='text-white text-[24px] leading-7 font-bold mb-4'>New Product <br />Waitlist coming soon</h1>
                                    <p className='text-[#AAAAAA] text-[14px] leading-4 mb-4'>Бидний шинэ бүтээгдэхүүнүүдийн мэдээллийг цаг алдалгүй авахыг хүсвэл имэйл хаягаа бидэнд үлдээгээрэй.</p>
                                    <div>
                                        <input
                                            type='text'
                                            id='email'
                                            name='email'
                                            value={email}
                                            onChange={onChangeEmail}
                                            className={`text-white border rounded-2xl py-3 w-full px-4 bg-inherit placeholder-[#3E3E3E] ${!validEmail.test(email) && email !== '' ?
                                                'border-red-400' : 'border-[#454545]'
                                                }
                                `}
                                            placeholder='Имэйл хаяг' />
                                        <div className='text-red-400 mt-1'>{emailErr}</div>
                                        <button onClick={!disableSendBtn ? submitEmail : null} type='submit' className={`flex justify-center text-white mt-5 gap-3 py-3 w-full duration-150 rounded-2xl ${disableSendBtn
                                            ? 'bg-[#CD5152]/30' : 'bg-[#CD5152] active:scale-95'
                                            }`}>
                                            <span className='text-[16px]'>Илгээх</span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <Footer />
                <Footer2 />
            </main>
        </>
    )
}

